sudo: true
service: docker
language: ruby
cache:
- bundler
before_install:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - gem install bundler -v 1.15
install:
- bundle install
rvm:
- 2.4.1

before_script:
  - docker run --name sensu-elasticsearch-6 -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -d docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
  - bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"

script:
- gem build sensu-plugins-elasticsearch.gemspec
- gem install sensu-plugins-elasticsearch-*.gem
- bundle exec rake quick

deploy:
- provider: script
  script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-elasticsearch
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
    
