language: ruby

cache:
  - bundler

install:
  - bundle install

rvm:
  - 2.4.1
  
script:
  - bundle exec rake default
  - gem build sensu-plugins-yieldbot.gemspec
  - gem install sensu-plugins-yieldbot-*.gem

before_deploy:
  - git clone https://github.com/sensu/sensu-go-bonsai-asset.git --branch feature/ruby-plugin-assets bonsai

deploy:
  - provider: script
    script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-yieldbot
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      rvm: 2.4.1
